version: 0.1
phases:
  install:
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - npm install
      - npm run build:production
  post_build:
    commands:
    #   - aws s3 cp dist s3://${S3_BUCKET} --recursive
    #   - aws configure set preview.cloudfront true
  #    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
